version: '3.8'

services:
  postgresql:
    image: postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d authentik -U authentik"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=authentik
      - POSTGRES_USER=authentik
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password
    networks:
      - projektwennerberg-net
    deploy:
      placement:
        constraints:
          - node.role == manager

  redis:
    image: redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 20s
    volumes:
      - redis:/data
    networks:
      - projektwennerberg-net

  server:
    image: ghcr.io/goauthentik/server:2025.6.3
    restart: unless-stopped
    command: server
    environment:
      - AUTHENTIK_SECRET_KEY=file:///run/secrets/authentik_secret_key
      - AUTHENTIK_POSTGRESQL__HOST=postgresql
      - AUTHENTIK_POSTGRESQL__USER=authentik
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=file:///run/secrets/postgres_password
      - AUTHENTIK_REDIS__HOST=redis
    volumes:
      - ./media:/media
      - ./custom-templates:/templates  
    secrets:
      - authentik_secret_key
      - postgres_password
    networks:
      - projektwennerberg-net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.authentik.rule=Host(`auth.projektwennerberg.org`)"
        - "traefik.http.routers.authentik.entrypoints=web"
        - "traefik.http.services.authentik.loadbalancer.server.port=9000"
        - "traefik.http.middlewares.authentik-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
        - "traefik.http.middlewares.authentik-headers.headers.customrequestheaders.X-Forwarded-For="
        - "traefik.http.routers.authentik.middlewares=authentik-headers"

  worker:
    image: ghcr.io/goauthentik/server:2025.6.3
    restart: unless-stopped
    command: worker
    user: root
    environment:
      - AUTHENTIK_SECRET_KEY=file:///run/secrets/authentik_secret_key
      - AUTHENTIK_POSTGRESQL__HOST=postgresql
      - AUTHENTIK_POSTGRESQL__USER=authentik
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=file:///run/secrets/postgres_password
      - AUTHENTIK_REDIS__HOST=redis
    volumes:
      - ./media:/media
      - ./custom-templates:/templates  
    secrets:
      - authentik_secret_key
      - postgres_password
    networks:
      - projektwennerberg-net
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  database:
  redis:
  # authentik-media:
  # authentik-templates:
  # authentik-certs:

secrets:
  postgres_password:
    external: true
  authentik_secret_key:
    external: true

networks:
  projektwennerberg-net:
    external: true
