version: '3.8'

services:
  hello:
    image: nginxdemos/hello:latest
    networks:
      - projektwennerberg-net
    deploy:
      labels:
        # 1. Enable Traefik for this service
        - "traefik.enable=true"

        # 4. Main router for the canonical domain (non-www)
        - "traefik.http.routers.hello.rule=Host(`projektwennerberg.org`)"
        - "traefik.http.routers.hello.entrypoints=web"
        - "traefik.http.routers.hello.service=hello"
        - "traefik.http.routers.hello.middlewares=authentik"

        - "traefik.http.services.hello.loadbalancer.server.port=80"


networks:
  projektwennerberg-net:
    external: true